Practicas/SegundoParcial_practica/Libreria-app/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\LibroController;
use App\Http\Controllers\EditorialController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('libro',LibroController::class);
Route::resource('dato',EditorialController::class);

Practicas/SegundoParcial_practica/Libreria-app/app/Models/Editorial.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Editorial extends Model
{
    use HasFactory;
    protected $fillable = [
        'nombre'
    ];
    public function libro() {
        return $this->hasMany(Libro::class,'editorial_id' , 'id');
    }
}

Practicas/SegundoParcial_practica/Libreria-app/app/Models/Libro.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Libro extends Model
{
    use HasFactory;
    protected $fillable =[
        'titulo',
        'editorial_id',
        'edicion',
        'pais',
        'precio'
    ];

    public function editorial()
    {
        return $this->belongsTo(Editorial::class,'editorial_id' , 'id');
    }
}

Practicas/SegundoParcial_practica/Libreria-app/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

Practicas/SegundoParcial_practica/Libreria-app/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

Practicas/SegundoParcial_practica/Libreria-app/app/Http/Controllers/EditorialController.php
<?php

namespace App\Http\Controllers;

use App\Models\Editorial;
use Illuminate\Http\Request;

class EditorialController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(Editorial $editorial)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Editorial $editorial)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Editorial $editorial)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Editorial $editorial)
    {
        //
    }
}

Practicas/SegundoParcial_practica/Libreria-app/app/Http/Controllers/LibroController.php
<?php

namespace App\Http\Controllers;

use App\Models\Libro;
use App\Models\Editorial;
use Illuminate\Http\Request;

class LibroController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        
        $libros = Libro::all();

        return view('Libro.index', [
            'libros' => $libros
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $editoriales=Editorial::all();
        return view('Libro.create',[
               'editoriales' => $editoriales
          ]
        );
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        // dd($request);
        $input = Libro::create($request->all());
        if($input){

            return redirect()->route('libro.index');
        }else{
            dd($request);

        }
    }

    /**
     * Display the specified resource.
     */
    public function show(Libro $libro)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Libro $libro)
    {
        $editoriales=Editorial::all();
        return view('Libro.edit',[
            'libro' => $libro, 'editoriales'=>$editoriales
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Libro $libro)
    {
        $input = $request->all();
        // dd($input);
        $libro->update($input);
        
        return redirect()->route('libro.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Libro $libro)
    {
        $libro->delete();
        return redirect()->route('libro.index');
    }
}

Practicas/SegundoParcial_practica/Libreria-app/resources/views/Libro/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<form class="w-full " action="{{route('libro.store')}}" method="POST">
    @csrf
    <div class="w-full flex flex-wrap -mx-3 mb-6">
        <div class="w-full md:w-1/6 px-3 mb-6 md:mb-0">
            <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="titulo">
                Titulo
            </label>
            <input
                class="appearance-none block w-full bg-gray-200 text-gray-700 border  rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white"
                id="titulo" type="text" name="titulo" placeholder="Titulo"
        </div>
        <div class="w-full md:w-1/3 px-3">
            <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="editorial_id"
                Editorial
            </label>
            <div class="relative">
                <select
                    class="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                    name="editorial_id" id="editorial_id">
                    @foreach ($editoriales as $editorial)
                    <option value="{{$editorial->id}}">{{$editorial->nombre}}</option>
                    @endforeach
                </select>
            </div>

        </div>
        <div class="w-full md:w-1/6 px-3">
            <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="edicion">
                Edicion
            </label>
            <input
                class="appearance-none block w-full bg-gray-200 text-gray-700 border  rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white"
                id="edicion" type="number" name="edicion" placeholder="edicion" >

        </div>
    </div>
    <div class="flex flex-wrap -mx-3 mb-6 w-full">
        <label for="pais">pais</label>
        <input type="text" name="pais" id="pais">
        <label for="precio">precio</label>
        <input type="number" name="precio" id="precio">
    </div>
    <div>
        <input type="submit" value="Registrar">
    </div>
</form>

</body>
</html>

Practicas/SegundoParcial_practica/Libreria-app/resources/views/Libro/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Editar Libro</h1>

    <form action="{{route('libro.update',$libro->id)}}" method="POST">
        @csrf
        @method('PUT')
        <div>
        <label for="titulo">Titulo</label>
        <input type="text" name="titulo" id="titulo" value="{{$libro->titulo}}">
        <label for="editorial_id">Editorial</label>
        <!-- <input type="number" name="editorial_id" id="editorial_id" value="{{$libro->editorial_id}}"> -->
        <select name="editorial_id" id="editorial_id">
            @foreach ($editoriales as $editorial){
                <option value="{{$editorial->id}}"{{$libro->editorial->id == $editorial->id ? 'selected' : ''}}>
                    {{ $editorial->nombre}}
                </option>
            }
            @endforeach
        </select>
        <label for="edicion">Edicion</label>
        <input type="number" name="edicion" id="edicion" value="{{$libro->edicion}}">
    </div>
    <div>
        <label for="pais">Pais</label>
        <input type="text" name="pais" id="pais" value="{{$libro->pais}}">
        <label for="precio">Precio</label>
        <input type="number" name="precio" id="precio" value="{{$libro->precio}}">
    </div>
    <div>
        <input type="submit" value="Actualizar">
    </div>
    </form>
    
</body>
</html>
    

Practicas/SegundoParcial_practica/Libreria-app/resources/views/Libro/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
<h1>Listado de clientes</h1>
<div class="flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
        <div class="overflow-hidden">
          <table class="min-w-full text-left text-sm font-light">
            <thead class="border-b font-medium">
              <tr>
                <th scope="col" class="px-6 py-4">Titulo</th>
                <th scope="col" class="px-6 py-4">editorial</th>
                <th scope="col" class="px-6 py-4">edicion</th>    
                <th scope="col" class="px-6 py-4">pais</th>
                <th scope="col" class="px-6 py-4">precio</th>

              </tr>
            </thead>
            <tbody>
                @foreach ($libros as $libro)
                <tr class="border-b">
                    <td class="whitespace-nowrap px-6 py-4">{{$libro->titulo}}</td>
                    <td class="whitespace-nowrap px-6 py-4">{{$libro->editorial->nombre}}</td>
                    <td class="whitespace-nowrap px-6 py-4">{{$libro->edicion}}</td>
                    <td class="whitespace-nowrap px-6 py-4">{{$libro->pais}}</td>
                    <td class="whitespace-nowrap px-6 py-4">{{$libro->precio}}</td>
                    <td><a href="{{route('libro.show',$libro->id)}}">Mostrar</a>
                        <a href="{{route('libro.edit',$libro->id)}}">Editar</a></td>
                    <td>
                        <form action="{{route('libro.destroy',$libro->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button type="submit">Eliminar</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>  
</body>
</html>

Practicas/SegundoParcial_practica/Libreria-app/resources/views/Libro/listado.blade.php
<x-app-layout>
    <x-slot name="header">
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">
          {{ __('Listado de clientes') }}{{$tipo_documento->descripcion}}
      </h2>
  </x-slot>

<table>
    <tr>
        <th>placa</th>
        
        <th>Numero Documento</th>    
        <th>nombre</th>
        <th>apellido</th>
        <th>telefono</th>
        <th>fecha nacimiento</th>
    </tr>
@foreach ($clientes as $cliente)
<tr>
    <td>{{$cliente->placa}}</td>
    
    <td>{{$cliente->numero_documento}}</td>
    <td>{{$cliente->nombre}}</td>
    <td>{{$cliente->apellido}}</td>
    <td>{{$cliente->telefono}}</td>
    <td>{{$cliente->fechanacimiento}}</td>
    <td><a href="{{route('cliente.show',$cliente->id)}}">Mostrar</a>
        <a href="{{route('cliente.edit',$cliente->id)}}">Editar</a></td>
    <td>
        <form action="{{route('cliente.destroy',$cliente->id)}}" method="post">
            @csrf
            @method('DELETE')
            <button type="submit">Eliminar</button>
        </form>
    </td>
</tr>
@endforeach
</table>    
<a href="{{route('cliente.create')}}">Registrar Cliente</a>
</x-app-layout>

Practicas/SegundoParcial_practica/Libreria-app/resources/views/Libro/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <ul>
        <li>Placa: {{$cliente->placa}}</li>
            <li>Tipo:{{$cliente->tipo_documento_id}}</li>
            <li>Doc:{{$cliente->numero_documento}}</li>
            <li>Nombre:{{$cliente->nombre}}</li>
            <li>Apellido{{$cliente->apellido}}</li>
            <li>Telefono:{{$cliente->telefono}}</li>
            <li>fecha:{{$cliente->fecha_nacimiento}}</li>
    </ul>
    <meta http-equiv="refresh" content="3; url={{route('cliente.index')}}" />

</body>
</html>