Practicas/Parqueo_Larabel/parqueo_arqui-app/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ClienteController;
use App\Http\Controllers\TarifaController;
use App\Http\Controllers\TiposDocumentoController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    // return view('welcome');
    return view('inicial');
});
Route::resource('cliente',ClienteController::class);
Route::resource('tarifa',TarifaController::class);
Route::get('tiposdocumento/{id}', [TiposDocumentoController::class,'listar'])->name('tiposdocumento.listar');

Practicas/Parqueo_Larabel/parqueo_arqui-app/app/Models/Cliente.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cliente extends Model
{
    use HasFactory;
    protected $fillable=[
    'placa',
    'tipo_documento_id',
    'numero_documento',
    'nombre',
    'apellido',
    'telefono',
    'fecha_nacimiento'];
    
    public function tipo_documento()
    {
        return $this->belongsTo(TiposDocumento::class,'tipo_documento_id' , 'id');
    }
}

Practicas/Parqueo_Larabel/parqueo_arqui-app/app/Models/Tarifa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tarifa extends Model
{
    use HasFactory;
    protected $fillable=[
        'descripcion',
        'precio',
        'hora'
        ];
}

Practicas/Parqueo_Larabel/parqueo_arqui-app/app/Models/TiposDocumento.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class TiposDocumento extends Model
{
    use HasFactory;
    protected $fillable=['descripcion'];
    public function clientes() {
        return $this->hasMany(Cliente::class,'tipo_documento_id' , 'id');
    }
}

Practicas/Parqueo_Larabel/parqueo_arqui-app/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

Practicas/Parqueo_Larabel/parqueo_arqui-app/app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use App\Models\Cliente;
use Illuminate\Http\Request;

class ClienteController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        
        $clientes = Cliente::all();
        return view('cliente.index', [
            'clientes' => $clientes
        ]);
        


    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
       return view('cliente.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $input = $request->all();
        
        return redirect()->route('cliente.index');
        
    
    }

    /**
     * Display the specified resource.
     */
    public function show(Cliente $cliente)
    {
        return view('cliente.show',[
            'cliente' => $cliente
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Cliente $cliente)
    {
        return view('cliente.edit',[
            'cliente' => $cliente
        ]);
        
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Cliente $cliente)
    {
        $input = $request->all();
        $cliente->update($input);
        return  view('cliente.show', [
            'cliente' => $cliente
        ]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Cliente $cliente)
    {
        $cliente->delete();
        return redirect()->route('cliente.index');

    }
}

Practicas/Parqueo_Larabel/parqueo_arqui-app/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

Practicas/Parqueo_Larabel/parqueo_arqui-app/app/Http/Controllers/TarifaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Tarifa;
use Illuminate\Http\Request;

class TarifaController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $tarifas = Tarifa::all();
        return view('tarifa.index',[
            'tarifas' => $tarifas
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('tarifa.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $input = $request->all();
        
        return redirect()->route('tarifa.index');
    }

    /**
     * Display the specified resource.
     */
    public function show(Tarifa $tarifa)
    {
        return  view('tarifa.show', [
            'tarifa' => $tarifa
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Tarifa $tarifa)
    {
        return view('tarifa.edit',[
            'tarifa' => $tarifa
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Tarifa $tarifa)
    {
        $input = $request->all();
        $tarifa->update($input);
        return  view('tarifa.show', [
            'tarifa' => $tarifa
        ]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Tarifa $tarifa)
    {
        $tarifa->delete();
        return redirect()->route('tarifa.index');
    }
}

Practicas/Parqueo_Larabel/parqueo_arqui-app/app/Http/Controllers/TiposDocumentoController.php
<?php

namespace App\Http\Controllers;

use App\Models\TiposDocumento;
use Illuminate\Http\Request;

class TiposDocumentoController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(TiposDocumento $tiposDocumento)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(TiposDocumento $tiposDocumento)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, TiposDocumento $tiposDocumento)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(TiposDocumento $tiposDocumento)
    {
        //
    }

    public function listar($id)
    {
        $tipo_documento=TiposDocumento::find($id);
        
        return view('cliente.listado',[
            'tipo_documento'=>$tipo_documento,
            'clientes'=>$tipo_documento->clientes
        ]);
    }
}

Practicas/Parqueo_Larabel/parqueo_arqui-app/resources/views/cliente/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <form action="{{route('cliente.store')}}" method="POST">
        @csrf
        <div>
        <label for="placa">Placa</label>
        <input type="text" name="placa" id="placa">
        <label for="tipo_documento_id">Tipo Documento</label>
        <input type="number" name="tipo_documento_id" id="tipo_documento_id">
        <label for="numero_documento">Numero Documento</label>
        <input type="number" name="numero_documento" id="numero_documento">
    </div>
    <div>
        <label for="nombre">Nombre</label>
        <input type="text" name="nombre" id="nombre">
        <label for="apellido">Apellido</label>
        <input type="text" name="apellido" id="apellido">
        <label for="telefono">Telefono</label>
        <input type="number" name="telefono" id="telefono">
        <label for="fecha_nacimiento">Fecha Nacimiento</label>
        <input type="date" name="fecha_nacimiento" id="fecha_nacimiento">
        
    </div>
    <div>
        <input type="submit" value="Registrar">
    </div>
    </form>
    
</body>
</html>

Practicas/Parqueo_Larabel/parqueo_arqui-app/resources/views/cliente/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

    <form action="{{route('cliente.update',$cliente->id)}}" method="POST">
        @csrf
        @method('PUT')
        <div>
        <label for="placa">Placa</label>
        <input type="text" name="placa" id="placa" value="{{$cliente->placa}}">
        <label for="tipo_documento_id">Tipo Documento</label>
        <input type="number" name="tipo_documento_id" id="tipo_documento_id" value="{{$cliente->tipo_documento_id}}">
        <label for="numero_documento">Numero Documento</label>
        <input type="number" name="numero_documento" id="numero_documento" value="{{$cliente->numero_documento}}">
    </div>
    <div>
        <label for="nombre">Nombre</label>
        <input type="text" name="nombre" id="nombre" value="{{$cliente->nombre}}">
        <label for="apellido">Apellido</label>
        <input type="text" name="apellido" id="apellido" value="{{$cliente->apellido}}">
        <label for="telefono">Telefono</label>
        <input type="number" name="telefono" id="telefono" value="{{$cliente->telefono}}">
        <label for="fecha_nacimiento">Fecha Nacimiento</label>
        <input type="date" name="fecha_nacimiento" id="fecha_nacimiento" value="{{$cliente->fecha_nacimiento}}">
        
    </div>
    <div>
        <input type="submit" value="Actualizar">
    </div>
    </form>
    
</body>
</html>

Practicas/Parqueo_Larabel/parqueo_arqui-app/resources/views/cliente/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<h1>Listado de clientes</h1>
<table>
    <tr>
        <th>placa</th>
        <th>tipodocumento</th>
        <th>Numero Documento</th>    
        <th>nombre</th>
        <th>apellido</th>
        <th>telefono</th>
        <th>fecha nacimiento</th>
    </tr>
@foreach ($clientes as $cliente)
<tr>
    <td>{{$cliente->placa}}</td>
    <td>{{$cliente->tipo_documento->descripcion}}</td>
    <td>{{$cliente->numero_documento}}</td>
    <td>{{$cliente->nombre}}</td>
    <td>{{$cliente->apellido}}</td>
    <td>{{$cliente->telefono}}</td>
    <td>{{$cliente->fechanacimiento}}</td>
    <td><a href="{{route('cliente.show',$cliente->id)}}">Mostrar</a>
        <a href="{{route('cliente.edit',$cliente->id)}}">Editar</a></td>
    <td>
        <form action="{{route('cliente.destroy',$cliente->id)}}" method="post">
            @csrf
            @method('DELETE')
            <button type="submit">Eliminar</button>
        </form>
    </td>
</tr>
@endforeach
</table>    
<a href="{{route('cliente.create')}}">Registrar Cliente</a>
</body>
</html>

Practicas/Parqueo_Larabel/parqueo_arqui-app/resources/views/cliente/listado.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<h1>Listado de clientes con {{$tipo_documento->descripcion}}</h1>
<table>
    <tr>
        <th>placa</th>
        
        <th>Numero Documento</th>    
        <th>nombre</th>
        <th>apellido</th>
        <th>telefono</th>
        <th>fecha nacimiento</th>
    </tr>
@foreach ($clientes as $cliente)
<tr>
    <td>{{$cliente->placa}}</td>
    
    <td>{{$cliente->numero_documento}}</td>
    <td>{{$cliente->nombre}}</td>
    <td>{{$cliente->apellido}}</td>
    <td>{{$cliente->telefono}}</td>
    <td>{{$cliente->fechanacimiento}}</td>
    <td><a href="{{route('cliente.show',$cliente->id)}}">Mostrar</a>
        <a href="{{route('cliente.edit',$cliente->id)}}">Editar</a></td>
    <td>
        <form action="{{route('cliente.destroy',$cliente->id)}}" method="post">
            @csrf
            @method('DELETE')
            <button type="submit">Eliminar</button>
        </form>
    </td>
</tr>
@endforeach
</table>    
<a href="{{route('cliente.create')}}">Registrar Cliente</a>
</body>
</html>

Practicas/Parqueo_Larabel/parqueo_arqui-app/resources/views/cliente/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <ul>
        <li>Placa: {{$cliente->placa}}</li>
            <li>Tipo:{{$cliente->tipo_documento_id}}</li>
            <li>Doc:{{$cliente->numero_documento}}</li>
            <li>Nombre:{{$cliente->nombre}}</li>
            <li>Apellido{{$cliente->apellido}}</li>
            <li>Telefono:{{$cliente->telefono}}</li>
            <li>fecha:{{$cliente->fecha_nacimiento}}</li>
    </ul>
    <meta http-equiv="refresh" content="3; url={{route('cliente.index')}}" />
</body>
</html>

Practicas/Parqueo_Larabel/parqueo_arqui-app/resources/views/tarifa/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<form action="{{route('tarifa.store')}}" method="POST">
        @csrf
        <div>
        <label for="hora">Hora</label>
        <input type="time" name="hora" id="hora">
        <label for="precio">Precio</label>
        <input type="number" name="precio" id="precio">
        <label for="descripcion">Descripcion</label>
        <input type="text" name="descripcion" id="descripcion">
    </div>
    <div>
        <input type="submit" value="Registrar">
    </div>
    </form>
    
</body>
</html>

Practicas/Parqueo_Larabel/parqueo_arqui-app/resources/views/tarifa/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

<form action="{{route('tarifa.update',$tarifa->id)}}" method="POST">
        @csrf
        @method('PUT')
        <div>
        <label for="hora">Hora</label>
        <input type="time" name="hora" id="hora" value="{{$tarifa->hora}}">
        <label for="precio">Precio</label>
        <input type="number" name="precio" id="precio" value="{{$tarifa->precio}}">
        <label for="descripcion">Descripcion</label>
        <input type="text" name="descripcion" id="descripcion" value="{{$tarifa->descripcion}}">
    </div>
    <div>
        <input type="submit" value="Registrar">
    </div>
    </form>
    
</body>
</html>

Practicas/Parqueo_Larabel/parqueo_arqui-app/resources/views/tarifa/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>

<h1>Listado de las tarifas</h1>
<table>
    <tr>
        <th>Hora</th>
        <th>Precio</th>
        <th>Descripcion</th>    
    </tr>
@foreach ($tarifas as $tarifa)
<tr>
    <td>{{$tarifa->hora}}</td>
    <td>{{$tarifa->precio}}</td>
    <td>{{$tarifa->descripcion}}</td>
    <td>{{$tarifa->fechanacimiento}}</td>
    <td><a href="{{route('tarifa.edit',$tarifa->id)}}">Editar</a></td>
    <td>
        <form action="{{route('tarifa.destroy',$tarifa->id)}}" method="post">
            @csrf
            @method('DELETE')
            <button type="submit">Eliminar</button>
        </form>
    </td>
</tr>
@endforeach
</table>    
<a href="{{route('tarifa.create')}}">Crear Tarifa</a>
</body>
</html>

Practicas/Parqueo_Larabel/parqueo_arqui-app/resources/views/tarifa/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <ul>
        <li>Hora :{{$tarifa->hora}}</li>
        <li>Precio :{{$tarifa->precio}}</li>
        <li>Descripcion :{{$tarifa->descripcion}}</li>
    </ul>
    <meta http-equiv="refresh" content="3; url={{route('tarifa.index')}}" />
</body>
</html>