Examenes/Final/final-app/routes/web.php
<?php

use App\Http\Controllers\CorrespondenciaController;
use App\Http\Controllers\DestinatarioController;
use App\Models\Correspondencia;
use App\Models\destinatario;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('correspondencia',CorrespondenciaController::class);
Route::resource('bestinatario',DestinatarioController::class);

Examenes/Final/final-app/app/Models/Correspondencia.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Correspondencia extends Model
{
    use HasFactory;
    protected $fillable =[
        'fecha',
        'remitente',
        'asunto',
        'cita',
        'destinatario_id'
    ];

    
    public function destinatario()
    {
        return $this->belongsTo(destinatario::class,'destinatario_id' , 'id');
    }
}

Examenes/Final/final-app/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

Examenes/Final/final-app/app/Models/destinatario.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class destinatario extends Model
{
    use HasFactory;
    protected $fillable =[
        'nombre',
        'cargo'
    ];
    public function correspondencia() {
        return $this->hasMany(Correspondencia::class,'destinatario_id' , 'id');
    }
}

Examenes/Final/final-app/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

Examenes/Final/final-app/app/Http/Controllers/CorrespondenciaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Correspondencia;
use App\Models\destinatario;
use Illuminate\Http\Request;

class CorrespondenciaController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $correspondencias = Correspondencia::all();

        return view('Correspondencia.index', [
            'correspondencias' => $correspondencias
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(Correspondencia $correspondencia)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Correspondencia $correspondencium)
    {
        $destinatarios=destinatario::all();
        return view('correspondencia.edit',[
            'correspondencia' => $correspondencium, 'destinatarios'=>$destinatarios
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Correspondencia $correspondencia)
    {
        $input = $request->all();
        // dd($input);
        $correspondencia->update($input);
        
        return redirect()->route('correspondencia.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Correspondencia $correspondencia)
    {
        //
    }
}

Examenes/Final/final-app/app/Http/Controllers/DestinatarioController.php
<?php

namespace App\Http\Controllers;

use App\Models\destinatario;
use Illuminate\Http\Request;

class DestinatarioController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(destinatario $destinatario)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(destinatario $destinatario)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, destinatario $destinatario)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(destinatario $destinatario)
    {
        //
    }
}

Examenes/Final/final-app/resources/views/Correspondencia/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<form class="w-full " action="{{route('correspondencia.store')}}" method="POST">
    @csrf
    <div class="w-full flex flex-wrap -mx-3 mb-6">
        <div class="w-full md:w-1/6 px-3 mb-6 md:mb-0">
            <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="titulo">
                Titulo
            </label>
            <input
                class="appearance-none block w-full bg-gray-200 text-gray-700 border  rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white"
                id="titulo" type="text" name="titulo" placeholder="Titulo"
        </div>
        <div class="w-full md:w-1/3 px-3">
            <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="editorial_id"
                Editorial
            </label>
            <div class="relative">
                <select
                    class="block appearance-none w-full bg-gray-200 border border-gray-200 text-gray-700 py-3 px-4 pr-8 rounded leading-tight focus:outline-none focus:bg-white focus:border-gray-500"
                    name="editorial_id" id="editorial_id">
                    @foreach ($editoriales as $editorial)
                    <option value="{{$editorial->id}}">{{$editorial->nombre}}</option>
                    @endforeach
                </select>
            </div>

        </div>
        <div class="w-full md:w-1/6 px-3">
            <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="edicion">
                Edicion
            </label>
            <input
                class="appearance-none block w-full bg-gray-200 text-gray-700 border  rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white"
                id="edicion" type="number" name="edicion" placeholder="edicion" >

        </div>
    </div>
    <div class="flex flex-wrap -mx-3 mb-6 w-full">
        <label for="pais">pais</label>
        <input type="text" name="pais" id="pais">
        <label for="precio">precio</label>
        <input type="number" name="precio" id="precio">
    </div>
    <div>
        <input type="submit" value="Registrar">
    </div>
</form>

</body>
</html>

Examenes/Final/final-app/resources/views/Correspondencia/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Editar Libro</h1>

    <form action="{{route('correspondencia.update',$correspondencia->id)}}" method="POST">
        @csrf
        @method('PUT')
        <div>
        <label for="fecha">fecha</label>
        <input type="date" name="fecha" id="fecha" value="{{$correspondencia->fecha}}">
        <label for="destinatario_id">destinatario</label>
        <!-- <input type="number" name="destinatario_id" id="destinatario_id" value="{{$correspondencia->destinatario_id}}"> -->
        <select name="destinatario_id" id="destinatario_id">
            @foreach ($destinatarios as $destinatario){
                <option value="{{$destinatario->id}}"{{$correspondencia->destinatario->id == $destinatario->id ? 'selected' : ''}}>
                    {{ $destinatario->nombre}}
                </option>
            }
            @endforeach
        </select>
        <label for="remitente">remitente</label>
        <input type="text" name="remitente" id="remitente" value="{{$correspondencia->remitente}}">
    </div>
    <div>
        <label for="asunto">asunto</label>
        <input type="text" name="asunto" id="asunto" value="{{$correspondencia->asunto}}">
        <label for="cita">cita</label>
        <input type="number" name="cita" id="cita" value="{{$correspondencia->cita}}">
    </div>
    <div>
        <input type="submit" value="Actualizar">
    </div>
    </form>
    
</body>
</html>
    

Examenes/Final/final-app/resources/views/Correspondencia/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
<h1>Listado de clientes</h1>
<div class="flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
        <div class="overflow-hidden">
          <table class="min-w-full text-left text-sm font-light">
            <thead class="border-b font-medium">
              <tr>
                <th scope="col" class="px-6 py-4">fecha</th>
                <th scope="col" class="px-6 py-4">remitente</th>
                <th scope="col" class="px-6 py-4">asunto</th>    
                <th scope="col" class="px-6 py-4">cita</th>
                <th scope="col" class="px-6 py-4">destinatario</th>

              </tr>
            </thead>
            <tbody>
                @foreach ($correspondencias as $correspondencia)
                <tr class="border-b">
                    <td class="whitespace-nowrap px-6 py-4">{{$correspondencia->fecha}}</td>
                    <td class="whitespace-nowrap px-6 py-4">{{$correspondencia->remitente}}</td>
                    <td class="whitespace-nowrap px-6 py-4">{{$correspondencia->asunto}}</td>
                    <td class="whitespace-nowrap px-6 py-4">{{$correspondencia->cita}}</td>
                    <td class="whitespace-nowrap px-6 py-4">{{$correspondencia->destinatario->nombre}}</td>
                    <td>
                        <a href="{{route('correspondencia.edit',$correspondencia->id)}}">Editar</a></td>
                    <td>
                    <!-- <td><a href="{{route('correspondencia.show',$correspondencia->id)}}">Mostrar</a>
                        <a href="{{route('correspondencia.edit',$correspondencia->id)}}">Editar</a></td>
                    <td> -->
                        <!-- <form action="{{route('correspondencia.destroy',$correspondencia->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button type="submit">Eliminar</button>
                        </form> -->
                    </td>
                </tr>
                @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>  
</body>
</html>

Examenes/Final/final-app/resources/views/Correspondencia/listado.blade.php
<x-app-layout>
    <x-slot name="header">
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">
          {{ __('Listado de clientes') }}{{$tipo_documento->descripcion}}
      </h2>
  </x-slot>

<table>
    <tr>
        <th>placa</th>
        
        <th>Numero Documento</th>    
        <th>nombre</th>
        <th>apellido</th>
        <th>telefono</th>
        <th>fecha nacimiento</th>
    </tr>
@foreach ($clientes as $cliente)
<tr>
    <td>{{$cliente->placa}}</td>
    
    <td>{{$cliente->numero_documento}}</td>
    <td>{{$cliente->nombre}}</td>
    <td>{{$cliente->apellido}}</td>
    <td>{{$cliente->telefono}}</td>
    <td>{{$cliente->fechanacimiento}}</td>
    <td><a href="{{route('cliente.show',$cliente->id)}}">Mostrar</a>
        <a href="{{route('cliente.edit',$cliente->id)}}">Editar</a></td>
    <td>
        <form action="{{route('cliente.destroy',$cliente->id)}}" method="post">
            @csrf
            @method('DELETE')
            <button type="submit">Eliminar</button>
        </form>
    </td>
</tr>
@endforeach
</table>    
<a href="{{route('cliente.create')}}">Registrar Cliente</a>
</x-app-layout>

Examenes/Final/final-app/resources/views/Correspondencia/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <ul>
        <li>Placa: {{$cliente->placa}}</li>
            <li>Tipo:{{$cliente->tipo_documento_id}}</li>
            <li>Doc:{{$cliente->numero_documento}}</li>
            <li>Nombre:{{$cliente->nombre}}</li>
            <li>Apellido{{$cliente->apellido}}</li>
            <li>Telefono:{{$cliente->telefono}}</li>
            <li>fecha:{{$cliente->fecha_nacimiento}}</li>
    </ul>
    <meta http-equiv="refresh" content="3; url={{route('cliente.index')}}" />

</body>
</html>