Practicas/Ejercicios_Examen_Final/Eje_3/Cine-app/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PeliculasController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('pelicula',PeliculasController::class);

Practicas/Ejercicios_Examen_Final/Eje_3/Cine-app/app/Models/Peliculas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Peliculas extends Model
{
    use HasFactory;

    protected $fillable = [
        'titulo',
        'artistas_principales',
        'anio',
        'productora',
        'genero'
    ];
}

Practicas/Ejercicios_Examen_Final/Eje_3/Cine-app/app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

Practicas/Ejercicios_Examen_Final/Eje_3/Cine-app/app/Models/pipocas.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class pipocas extends Model
{
    use HasFactory;
    protected $fillable = [
        'tamano',
        'precio'
    ];
}

Practicas/Ejercicios_Examen_Final/Eje_3/Cine-app/app/Models/soda.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class soda extends Model
{
    use HasFactory;
    protected $fillable = [
        'tamano',
        'precio'
    ];
}

Practicas/Ejercicios_Examen_Final/Eje_3/Cine-app/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

Practicas/Ejercicios_Examen_Final/Eje_3/Cine-app/app/Http/Controllers/PeliculasController.php
<?php

namespace App\Http\Controllers;

use App\Models\Peliculas;
use Illuminate\Http\Request;

class PeliculasController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $peliculas = Peliculas::all();

        return view('peliculas.index', [
            'peliculas' => $peliculas
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('peliculas.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
           // dd($request);
        $input = Peliculas::create($request->all());
        if($input){

            return redirect()->route('pelicula.index');
        }else{
            dd($request);

        }
    }

    /**
     * Display the specified resource.
     */
    public function show(Peliculas $peliculas)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Peliculas $peliculas)
    {
        return view('peliculas.edit',[
            'pelicula' => $peliculas
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Peliculas $peliculas)
    {
        $input = $request->all();
        // dd($input);
        $peliculas->update($input);
        
        return redirect()->route('pelicula.index');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Peliculas $peliculas)
    {
        // dd($peliculas);
        $peliculas->delete();
        return redirect()->route('pelicula.index');
    }
}

Practicas/Ejercicios_Examen_Final/Eje_3/Cine-app/app/Http/Controllers/PipocasController.php
<?php

namespace App\Http\Controllers;

use App\Models\pipocas;
use Illuminate\Http\Request;

class PipocasController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(pipocas $pipocas)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(pipocas $pipocas)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, pipocas $pipocas)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(pipocas $pipocas)
    {
        //
    }
}

Practicas/Ejercicios_Examen_Final/Eje_3/Cine-app/app/Http/Controllers/SodaController.php
<?php

namespace App\Http\Controllers;

use App\Models\soda;
use Illuminate\Http\Request;

class SodaController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(soda $soda)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(soda $soda)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, soda $soda)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(soda $soda)
    {
        //
    }
}

Practicas/Ejercicios_Examen_Final/Eje_3/Cine-app/resources/views/peliculas/create.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<form class="w-full " action="{{route('pelicula.store')}}" method="POST">
    @csrf
    <div class="w-full flex flex-wrap -mx-3 mb-6">
        <div class="w-full md:w-1/6 px-3 mb-6 md:mb-0">
            <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="titulo">
                Titulo
            </label>
            <input
                class="appearance-none block w-full bg-gray-200 text-gray-700 border  rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white"
                id="titulo" type="text" name="titulo" placeholder="Titulo">
        </div>
        <div class="w-full md:w-1/3 px-3">
            <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="editorial_id">
                Artistas Principales
            </label>
            <input
                class="appearance-none block w-full bg-gray-200 text-gray-700 border  rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white"
                id="artistas_principales" type="text" name="artistas_principales" placeholder="artistas_principales">
            </div>

        </div>
        <div class="w-full md:w-1/6 px-3">
            <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="anio">
                Año
            </label>
            <input
                class="appearance-none block w-full bg-gray-200 text-gray-700 border  rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white"
                id="anio" type="number" name="anio" placeholder="anio" >

        </div>
    </div>
    <div class="flex flex-wrap -mx-3 mb-6 w-full">
        <label for="productora">Productora</label>
        <input type="text" name="productora" id="productora">
        <label for="genero">Genero</label>
        <input type="text" name="genero" id="genero">
    </div>
    <div>
        <input type="submit" value="Registrar">
    </div>
</form>

</body>
</html>

Practicas/Ejercicios_Examen_Final/Eje_3/Cine-app/resources/views/peliculas/edit.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Editar pelicula</h1>

    <form action="{{route('pelicula.update', $pelicula->id)}}" method="POST">
        @csrf
        @method('PUT')
        <div>
        <label for="titulo">Titulo</label>
        <input type="text" name="titulo" id="titulo" value="{{$pelicula->titulo}}">
        <label for="artistas_principales">Artistas Prinicpales</label>
        <input type="text" name="artistas_principales" id="artistas_principales" value="{{$pelicula->artistas_principales}}">
        <label for="anio">Año</label>
        <input type="number" name="anio" id="anio" value="{{$pelicula->anio}}">
    </div>
    <div>
        <label for="productora">Productora</label>
        <input type="text" name="productora" id="productora" value="{{$pelicula->productora}}">
        <label for="genero">Genero</label>
        <input type="text" name="genero" id="genero" value="{{$pelicula->genero}}">
    </div>
    <div>
        <input type="submit" value="Actualizar">
    </div>
    </form>
    
</body>
</html>
    

Practicas/Ejercicios_Examen_Final/Eje_3/Cine-app/resources/views/peliculas/index.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
<h1>Listado de Peliculas</h1>
<div class="flex flex-col">
    <div class="overflow-x-auto sm:-mx-6 lg:-mx-8">
      <div class="inline-block min-w-full py-2 sm:px-6 lg:px-8">
        <div class="overflow-hidden">
          <table class="min-w-full text-left text-sm font-light">
            <thead class="border-b font-medium">
              <tr>
                <th scope="col" class="px-6 py-4">Titulo</th>
                <th scope="col" class="px-6 py-4">artistas principales</th>
                <th scope="col" class="px-6 py-4">año</th>    
                <th scope="col" class="px-6 py-4">productora</th>
                <th scope="col" class="px-6 py-4">gemero</th>

              </tr>
            </thead>
            <tbody>
                @foreach ($peliculas as $pelicula)
                <tr class="border-b">
                    <td class="whitespace-nowrap px-6 py-4">{{$pelicula->titulo}}</td>
                    <td class="whitespace-nowrap px-6 py-4">{{$pelicula->artistas_principales}}</td>
                    <td class="whitespace-nowrap px-6 py-4">{{$pelicula->anio}}</td>
                    <td class="whitespace-nowrap px-6 py-4">{{$pelicula->productora}}</td>
                    <td class="whitespace-nowrap px-6 py-4">{{$pelicula->genero}}</td>
                    <td><a href="{{route('pelicula.show',$pelicula->id)}}">Mostrar</a>
                        <a href="{{route('pelicula.edit',$pelicula->id)}}">Editar</a></td>
                    <td>
                        <form action="{{route('pelicula.destroy',$pelicula->id)}}" method="post">
                            @csrf
                            @method('DELETE')
                            <button type="submit">Eliminar</button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>  
</body>
</html>

Practicas/Ejercicios_Examen_Final/Eje_3/Cine-app/resources/views/peliculas/listado.blade.php
<x-app-layout>
    <x-slot name="header">
      <h2 class="font-semibold text-xl text-gray-800 leading-tight">
          {{ __('Listado de clientes') }}{{$tipo_documento->descripcion}}
      </h2>
  </x-slot>

<table>
    <tr>
        <th>placa</th>
        
        <th>Numero Documento</th>    
        <th>nombre</th>
        <th>apellido</th>
        <th>telefono</th>
        <th>fecha nacimiento</th>
    </tr>
@foreach ($clientes as $cliente)
<tr>
    <td>{{$cliente->placa}}</td>
    
    <td>{{$cliente->numero_documento}}</td>
    <td>{{$cliente->nombre}}</td>
    <td>{{$cliente->apellido}}</td>
    <td>{{$cliente->telefono}}</td>
    <td>{{$cliente->fechanacimiento}}</td>
    <td><a href="{{route('cliente.show',$cliente->id)}}">Mostrar</a>
        <a href="{{route('cliente.edit',$cliente->id)}}">Editar</a></td>
    <td>
        <form action="{{route('cliente.destroy',$cliente->id)}}" method="post">
            @csrf
            @method('DELETE')
            <button type="submit">Eliminar</button>
        </form>
    </td>
</tr>
@endforeach
</table>    
<a href="{{route('cliente.create')}}">Registrar Cliente</a>
</x-app-layout>

Practicas/Ejercicios_Examen_Final/Eje_3/Cine-app/resources/views/peliculas/show.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <ul>
        <li>Placa: {{$cliente->placa}}</li>
            <li>Tipo:{{$cliente->tipo_documento_id}}</li>
            <li>Doc:{{$cliente->numero_documento}}</li>
            <li>Nombre:{{$cliente->nombre}}</li>
            <li>Apellido{{$cliente->apellido}}</li>
            <li>Telefono:{{$cliente->telefono}}</li>
            <li>fecha:{{$cliente->fecha_nacimiento}}</li>
    </ul>
    <meta http-equiv="refresh" content="3; url={{route('cliente.index')}}" />

</body>
</html>